steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/ninecodingchallege:${SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/ninecodingchallege"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "$PROJECT_ID",
        "--region=us-central1",
        "--platform=managed",
        "--image=gcr.io/$PROJECT_ID/ninecodingchallege:${SHORT_SHA}",
      ]
